version: '2'

services:
  sia:
    build: 
      context: ./sia
    volumes:
      - ./sia-data/:/var/sia-data
    restart:
      always
    ports:
      - "3333:3333"
  ccminer:
    build:
      context: ./ccminer
    volumes_from:
      - sia
    links:
      - sia
